### ISSUE TITLE
User state reset on Password page

### ISSUE THREAD

**Issue by tkaraivanov** [worbli/portalBackEnd#14]
It seems that the first time a user clicks on Password after signing up for an account and advancing their state to started/approved, the account state is being reset to "default" in local storage. Logging out and back in results in the correct user state being applied, and clicking on Password no longer results in this problem. It appears that it only happens the first time with new portal accounts.

**Comment by tkaraivanov** [comment]
I could reproduce this twice, but I can no longer reproduce it. Not sure how to recreate the conditions.

**Comment by bkawk** [comment]
I spent about an hour trying to recreate this, lets keep an eye on it and if we figure out how to recreate it we can fix it, I've also started a code review in the xrm doc maybe it can reveal this
