### ISSUE TITLE
Calendar date picker for BoD

### ISSUE THREAD

**Issue by tkaraivanov** [worbli/portalBackEnd#17]
Change the DoB selector to a calendar picker.

(apparently it's a top5 customer support issue where people get their date and month swapped)

**Comment by bkawk** [comment]
The Month has 

1- Jan, 
2 - Fab
3- Mar

how can users think that these are days? 
IMO Date pickers are great for months and years close to the current month like for tholiday bookings but are terrible forDOB, please confirm you want this

**Comment by tkaraivanov** [comment]
An alternative approach would be to change the months in the dropdown to:
Jan
Feb
Mar
(remove the numbers in front)

so users can't choose them using tab-number.

I don't know how users are becoming confused, but apparently it's a common issue and lots of users are getting their KYC rejected due to that.

**Comment by bkawk** [comment]
The User will see the dates name in full, ie January, February etc and will no longer see that confusing number!

![Screenshot 2018-12-04 at 08.40.20.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56e969973a5bda1300faf627/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417753e7950e32a64c5b370f1162b4f5d5f5cb053181d1ba6acda6fb4bc2e75d80a5fe9d7385e77c13e15a8ea821eb801ec20d94880b6ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4fcb50fe4fe14956ad133771ab.png)
