### ISSUE TITLE
Email verification link should expire on use

### ISSUE THREAD

**Issue by tkaraivanov** [worbli/portalBackEnd#21]
Make the email verification link expire once it's used once.

**Comment by bkawk** [comment]
- [ ] Save JWT, email, to a new collection called 'actice_jwt' when a user joins and when password reset, remove any previous tokens for users
- [ ]  Before saving the password to the database, check the 'actice_jwt' collection
- [ ] After set password update the  'actice_jwt'  collection to show the jwt was used
- [ ] test to make sure only one user can ever be in 'actice_jwt'
- [ ] test to make sure only active jwt's can set a password

**Comment by colinskeep** [comment]
The front end needs to be updated so that after following the forget password link or the confirm email link you PUT to /password/ instead of POST.

**Comment by colinskeep** [comment]
From the password page: 
- [ ]  Check if user is logged in or not
- [ ]  If user is logged in, update POST endpoint to /updatePassword/
- [ ]  If user is not logged in, update POST endpoint to /password/
- [ ]  If user posts to /password/ endpoint and fails, alert user that their token is expired
