### ISSUE TITLE
ensure integrity of the user's jwt

### ISSUE THREAD

**Issue by tkaraivanov** [worbli/portalBackEnd#53]
Each time the API is called, check the JWT is in the correct state. If not, update the user jwt and then respond to the API request including the new jwt.

**Comment by bkawk** [comment]
There are many functions that were written in a hurry that need to be refactored before this work is done IMO.

**Comment by bitmodeler** [comment]
Made two helper routines for accomplishing this. One generates a new web token based on the current onfido_status. The other generates a "thenable" that gets passed the onfido_status in an object, accommodating up-to-the-moment vetting of a user's onfido_status.

The latter routine can be integrated into the existing codebase just before any point where an onfido_status gets checked; or the _algorithm_ of such a routine could be integrated into a future rewrite of the portal back end.

Verbatim from the commit:
============================================================
Added "getUpdatedOnfidoStatus" to v2/controllers/kyc.js; generates a new web token containing a possibly updated onfido_status.

Also added "getOnfido" to v2/components/onfido.js; returns a "thenable" that gets passed a user's onfido_status, accommodating easy up-to-the-moment validation.

[The onfido_status in both cases is retrieved from the Users collection for a given Email address...]
